import React from 'react';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow, Tag } from '@carbon/react';
import { type ShaClaim } from './claims-accounting.resource';
import { splitBillForSha, money } from './bill-utils';
import styles from './invoice-document.component.scss';

interface InvoiceDocumentProps {
  claim: ShaClaim;
}

/** Printable system-generated invoice for a claim's companion bill (SHA / copay split). */
const InvoiceDocument = React.forwardRef<HTMLDivElement, InvoiceDocumentProps>(({ claim }, ref) => {
  const split = splitBillForSha(claim.lines);
  const invoiceNo = claim.bill?.billNo ?? claim.claimCode.replace('CLM', 'INV');

  return (
    <div className={styles.invoice} ref={ref}>
      <div className={styles.invoiceHead}>
        <div>
          <div className={styles.invoiceNo}>{invoiceNo}</div>
          <div className={styles.invoiceFor}>
            {claim.patientName} · CR {claim.crNumber}
          </div>
          <div className={styles.invoiceMeta}>
            {claim.fund} · {claim.serviceType === 'INPATIENT' ? 'Inpatient' : 'Outpatient'} · Claim {claim.claimCode}
          </div>
        </div>
        <Tag type="blue" size="sm">
          Auto-generated
        </Tag>
      </div>

      <div className={styles.tableWrap}>
        <Table size="sm" aria-label="invoice lines" useZebraStyles>
          <TableHead>
            <TableRow>
              <TableHeader>Code</TableHeader>
              <TableHeader>Description</TableHeader>
              <TableHeader className={styles.num}>Qty</TableHeader>
              <TableHeader className={styles.num}>Charge</TableHeader>
              <TableHeader className={styles.num}>SHA covered</TableHeader>
              <TableHeader className={styles.num}>Copay</TableHeader>
              <TableHeader>Payer</TableHeader>
            </TableRow>
          </TableHead>
          <TableBody>
            {split.lines.map((l) => (
              <TableRow key={l.line.code}>
                <TableCell className={styles.mono}>{l.line.code}</TableCell>
                <TableCell>{l.line.description}</TableCell>
                <TableCell className={styles.num}>{l.line.quantity}</TableCell>
                <TableCell className={styles.num}>{money(l.lineTotal)}</TableCell>
                <TableCell className={styles.num}>{l.shaCovered ? money(l.shaCovered) : '—'}</TableCell>
                <TableCell className={styles.num}>{l.copay ? money(l.copay) : '—'}</TableCell>
                <TableCell>
                  <Tag size="sm" type={l.payer === 'SHA' ? 'green' : 'red'}>
                    {l.payer}
                  </Tag>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>

      <div className={styles.totals}>
        <div className={styles.totalRow}>
          <span>Total charge</span>
          <strong>{money(split.totalCharge)}</strong>
        </div>
        <div className={styles.totalRow}>
          <span>SHA covered</span>
          <span className={styles.sha}>{money(split.shaCovered)}</span>
        </div>
        <div className={styles.totalRow}>
          <span>Copay due</span>
          <span className={styles.copay}>{split.copay ? money(split.copay) : 'None — fully covered by SHA'}</span>
        </div>
      </div>

      <p className={styles.note}>
        This invoice is generated by the system and attached to the claim as a supporting document on submission.
      </p>
    </div>
  );
});

InvoiceDocument.displayName = 'InvoiceDocument';

export default InvoiceDocument;
