/**
 * Bill ↔ claim helpers.
 *
 * A bill is the ledger (line items). A SHA claim is the SHA-payable slice of that
 * bill; the remainder is the patient's copay (cash). Cash-only payers have no
 * claim at all — every line is paid out of pocket, before the service.
 */
import { type ClaimLine, type ShaClaim } from './claims-accounting.resource';

export type PaymentMode = 'SHA' | 'CASH' | 'INSURANCE';

export interface BillLineSplit {
  line: ClaimLine;
  lineTotal: number;
  /** Amount the fund (SHA) pays for this line — capped at the tariff. */
  shaCovered: number;
  /** Amount the patient pays for this line (copay / cash). */
  copay: number;
  /** Who settles the patient portion at the point of service. */
  payer: 'SHA' | 'Cash';
}

export interface BillSplit {
  totalCharge: number;
  shaCovered: number;
  copay: number;
  lines: BillLineSplit[];
  /** SHA-payable lines only — this is what the claim carries. */
  claimLines: ClaimLine[];
}

/**
 * Split a bill's line items into the SHA-payable slice and the copay/cash slice.
 *
 * - SHA pays each line up to its tariff; any excess over tariff is a copay.
 * - Cash / out-of-pocket insurance: the whole line is paid by the patient (no SHA).
 * - Fully covered by SHA is just the case where every line's charge ≤ tariff (copay 0).
 */
export function splitBillForSha(lines: ClaimLine[], mode: PaymentMode = 'SHA'): BillSplit {
  const split: BillLineSplit[] = [];
  const claimLines: ClaimLine[] = [];
  let totalCharge = 0;
  let shaCovered = 0;
  let copay = 0;

  for (const line of lines) {
    const lineTotal = line.unitPrice * line.quantity;
    totalCharge += lineTotal;

    if (mode === 'SHA') {
      const covered = Math.min(line.unitPrice, line.tariff) * line.quantity;
      const excess = lineTotal - covered;
      shaCovered += covered;
      copay += excess;
      if (covered > 0) {
        claimLines.push({ ...line, unitPrice: Math.min(line.unitPrice, line.tariff) });
      }
      split.push({ line, lineTotal, shaCovered: covered, copay: excess, payer: excess > 0 ? 'Cash' : 'SHA' });
    } else {
      // Cash / insurance out-of-pocket — the patient pays the whole line before service.
      copay += lineTotal;
      split.push({ line, lineTotal, shaCovered: 0, copay: lineTotal, payer: 'Cash' });
    }
  }

  return { totalCharge, shaCovered, copay, lines: split, claimLines };
}

export type ClaimDocumentType = 'INVOICE' | 'COPAY_RECEIPT' | 'REFERRAL' | 'LAB_REQUEST' | 'OTHER';

export interface ClaimDocument {
  id: string;
  name: string;
  type: ClaimDocumentType;
  /** System-produced (e.g. the invoice) vs. uploaded by staff. */
  autoGenerated: boolean;
  /** Whether an in-app preview is available (the invoice is rendered from the bill). */
  previewable: boolean;
}

/**
 * The supporting documents attached to a claim on submission. The invoice is
 * always present and auto-generated from the bill; a copay receipt is added when
 * there is a copay; anything staff uploaded is appended.
 */
export function buildClaimDocuments(claim: ShaClaim): ClaimDocument[] {
  const split = splitBillForSha(claim.lines);
  const invoiceNo = claim.bill?.billNo ?? claim.claimCode.replace('CLM', 'INV');

  const docs: ClaimDocument[] = [
    {
      id: `${claim.id}-invoice`,
      name: `${invoiceNo}.pdf`,
      type: 'INVOICE',
      autoGenerated: true,
      previewable: true,
    },
  ];

  if (split.copay > 0) {
    docs.push({
      id: `${claim.id}-copay`,
      name: `${invoiceNo}-copay-receipt.pdf`,
      type: 'COPAY_RECEIPT',
      autoGenerated: false,
      previewable: false,
    });
  }

  for (const name of claim.attachments ?? []) {
    const type: ClaimDocumentType = /referral/i.test(name)
      ? 'REFERRAL'
      : /lab|request/i.test(name)
        ? 'LAB_REQUEST'
        : 'OTHER';
    docs.push({ id: `${claim.id}-${name}`, name, type, autoGenerated: false, previewable: false });
  }

  return docs;
}

const DOC_TYPE_LABEL: Record<ClaimDocumentType, string> = {
  INVOICE: 'System invoice',
  COPAY_RECEIPT: 'Copay receipt',
  REFERRAL: 'Referral letter',
  LAB_REQUEST: 'Lab request',
  OTHER: 'Attachment',
};

export function claimDocumentLabel(type: ClaimDocumentType): string {
  return DOC_TYPE_LABEL[type];
}

export const money = (n: number) => `KES ${n.toLocaleString('en-KE')}`;
