import React from 'react';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow, Tag } from '@carbon/react';
import { itemStatus, type CashBill } from './cash-checklist.resource';
import styles from './bill-document.component.scss';

const money = (n: number) => `KES ${n.toLocaleString('en-KE')}`;
const ITEM_TAG = { UNPAID: 'gray', PARTIAL: 'blue', PAID: 'green' } as const;
const ITEM_LABEL = { UNPAID: 'Unpaid', PARTIAL: 'Partial', PAID: 'Paid' } as const;

interface BillDocumentProps {
  bill: CashBill;
  kind: 'invoice' | 'receipt';
}

/** Printable invoice (pending) or receipt (paid) for a cash bill. */
const BillDocument = React.forwardRef<HTMLDivElement, BillDocumentProps>(({ bill, kind }, ref) => {
  const total = bill.lineItems.reduce((sum, i) => sum + i.amount, 0);
  const paid = bill.lineItems.reduce((sum, i) => sum + i.paidAmount, 0);
  const balance = total - paid;
  const isReceipt = kind === 'receipt';

  return (
    <div className={styles.doc} ref={ref}>
      <div className={styles.docHead}>
        <div>
          <div className={styles.docNo}>{bill.billNo}</div>
          <div className={styles.docFor}>
            {bill.patientName} · CR {bill.crNumber}
          </div>
          <div className={styles.docMeta}>
            {bill.date} · {bill.source === 'SHA_COPAY' ? `SHA copay · ${bill.claimCode}` : 'Cash'}
          </div>
        </div>
        <Tag type={isReceipt ? 'green' : 'blue'} size="sm">
          {isReceipt ? 'Receipt · Paid' : 'Invoice'}
        </Tag>
      </div>

      <div className={styles.tableWrap}>
        <Table size="sm" aria-label="bill lines" useZebraStyles>
          <TableHead>
            <TableRow>
              <TableHeader>Code</TableHeader>
              <TableHeader>Service</TableHeader>
              <TableHeader className={styles.num}>Amount</TableHeader>
              <TableHeader>Status</TableHeader>
              {isReceipt ? <TableHeader>Receipt</TableHeader> : null}
            </TableRow>
          </TableHead>
          <TableBody>
            {bill.lineItems.map((i) => {
              const st = itemStatus(i);
              const receipts = bill.payments
                .filter((p) => p.itemId === i.id)
                .map((p) => p.receiptNo)
                .join(', ');
              return (
                <TableRow key={i.id}>
                  <TableCell className={styles.mono}>{i.code}</TableCell>
                  <TableCell>{i.service}</TableCell>
                  <TableCell className={styles.num}>{money(i.amount)}</TableCell>
                  <TableCell>
                    <Tag size="sm" type={ITEM_TAG[st]}>
                      {ITEM_LABEL[st]}
                    </Tag>
                  </TableCell>
                  {isReceipt ? <TableCell className={styles.mono}>{receipts || '—'}</TableCell> : null}
                </TableRow>
              );
            })}
          </TableBody>
        </Table>
      </div>

      <div className={styles.totals}>
        <div className={styles.totalRow}>
          <span>Total</span>
          <strong>{money(total)}</strong>
        </div>
        <div className={styles.totalRow}>
          <span>Paid</span>
          <span className={styles.paid}>{money(paid)}</span>
        </div>
        <div className={styles.totalRow}>
          <span>Balance</span>
          <span className={styles.balance}>{balance ? money(balance) : 'Settled in full'}</span>
        </div>
      </div>

      <p className={styles.note}>
        {isReceipt
          ? 'Official receipt for cash received. Generated by the system.'
          : 'Invoice for the outstanding balance. Present at the cash point to settle before service.'}
      </p>
    </div>
  );
});

BillDocument.displayName = 'BillDocument';

export default BillDocument;
